------------------------------------------------------------------------
-- X12 EDI Pipeline: Raw to Analytics
-- Companion SQL for: "From 300MB EDI Files to AI-Enriched Claims in 15 Minutes"
-- Prerequisites: ACCOUNTADMIN role, APP_WH warehouse, AI_COMPLETE access
------------------------------------------------------------------------

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE APP_WH;

------------------------------------------------------------------------
-- BRONZE LAYER
------------------------------------------------------------------------

CREATE DATABASE IF NOT EXISTS X12_EDI_AI;
CREATE SCHEMA IF NOT EXISTS X12_EDI_AI.STAGING;

CREATE OR REPLACE TABLE X12_EDI_AI.STAGING.LANDING_X12_RAW (
    MESSAGE_ID          VARCHAR(100),
    TRANSACTION_TYPE    VARCHAR(10),
    RAW_X12_DATA        VARCHAR(16777216) NOT NULL,
    SOURCE_SYSTEM       VARCHAR(100),
    INGESTION_TIMESTAMP VARCHAR(100)
);

------------------------------------------------------------------------
-- SILVER LAYER
------------------------------------------------------------------------

CREATE SCHEMA IF NOT EXISTS X12_EDI_AI.SILVER;

CREATE OR REPLACE DYNAMIC TABLE X12_EDI_AI.SILVER.SILVER_X12_SEGMENTS
    TARGET_LAG = '5 minutes'
    WAREHOUSE = APP_WH
AS
SELECT
    r.MESSAGE_ID,
    r.SOURCE_SYSTEM,
    r.INGESTION_TIMESTAMP,
    seg.INDEX AS SEGMENT_POSITION,
    TRIM(seg.VALUE) AS RAW_SEGMENT,
    SPLIT_PART(TRIM(seg.VALUE), '*', 1) AS SEGMENT_ID,
    TRIM(seg.VALUE) AS SEGMENT_DATA
FROM X12_EDI_AI.STAGING.LANDING_X12_RAW r,
    LATERAL SPLIT_TO_TABLE(r.RAW_X12_DATA, '~') seg
WHERE TRIM(seg.VALUE) != '';

CREATE OR REPLACE DYNAMIC TABLE X12_EDI_AI.SILVER.SILVER_CLAIMS_HEADER
    TARGET_LAG = '5 minutes'
    WAREHOUSE = APP_WH
AS
SELECT
    MESSAGE_ID,
    SPLIT_PART(SEGMENT_DATA, '*', 2) AS CLAIM_ID,
    TRY_TO_DECIMAL(SPLIT_PART(SEGMENT_DATA, '*', 3), 12, 2) AS TOTAL_BILLED_AMOUNT,
    SPLIT_PART(SEGMENT_DATA, '*', 6) AS PLACE_OF_SERVICE_CODE,
    SOURCE_SYSTEM,
    INGESTION_TIMESTAMP
FROM X12_EDI_AI.SILVER.SILVER_X12_SEGMENTS
WHERE SEGMENT_ID = 'CLM';

CREATE OR REPLACE DYNAMIC TABLE X12_EDI_AI.SILVER.SILVER_PATIENTS
    TARGET_LAG = '5 minutes'
    WAREHOUSE = APP_WH
AS
WITH patient_nm1 AS (
    SELECT
        MESSAGE_ID,
        SPLIT_PART(SEGMENT_DATA, '*', 4) AS PATIENT_LAST_NAME,
        SPLIT_PART(SEGMENT_DATA, '*', 5) AS PATIENT_FIRST_NAME,
        SPLIT_PART(SEGMENT_DATA, '*', 10) AS MEMBER_ID,
        SEGMENT_POSITION
    FROM X12_EDI_AI.SILVER.SILVER_X12_SEGMENTS
    WHERE SEGMENT_ID = 'NM1' AND SPLIT_PART(SEGMENT_DATA, '*', 2) = 'IL'
),
patient_dmg AS (
    SELECT
        MESSAGE_ID,
        SPLIT_PART(SEGMENT_DATA, '*', 3) AS DATE_OF_BIRTH,
        SPLIT_PART(SEGMENT_DATA, '*', 4) AS GENDER_CODE
    FROM X12_EDI_AI.SILVER.SILVER_X12_SEGMENTS
    WHERE SEGMENT_ID = 'DMG'
)
SELECT
    n.MESSAGE_ID,
    n.PATIENT_LAST_NAME,
    n.PATIENT_FIRST_NAME,
    n.MEMBER_ID,
    TRY_TO_DATE(d.DATE_OF_BIRTH, 'YYYYMMDD') AS DATE_OF_BIRTH,
    CASE d.GENDER_CODE WHEN 'M' THEN 'Male' WHEN 'F' THEN 'Female' ELSE 'Unknown' END AS GENDER
FROM patient_nm1 n
LEFT JOIN patient_dmg d ON n.MESSAGE_ID = d.MESSAGE_ID;

CREATE OR REPLACE DYNAMIC TABLE X12_EDI_AI.SILVER.SILVER_PROVIDERS
    TARGET_LAG = '5 minutes'
    WAREHOUSE = APP_WH
AS
SELECT
    MESSAGE_ID,
    SPLIT_PART(SEGMENT_DATA, '*', 2) AS PROVIDER_TYPE_CODE,
    CASE SPLIT_PART(SEGMENT_DATA, '*', 2)
        WHEN '85' THEN 'Billing'
        WHEN '82' THEN 'Rendering'
        WHEN '41' THEN 'Submitter'
        ELSE 'Other'
    END AS PROVIDER_ROLE,
    SPLIT_PART(SEGMENT_DATA, '*', 4) AS PROVIDER_NAME,
    SPLIT_PART(SEGMENT_DATA, '*', 5) AS PROVIDER_FIRST_NAME,
    SPLIT_PART(SEGMENT_DATA, '*', 9) AS ID_QUALIFIER,
    SPLIT_PART(SEGMENT_DATA, '*', 10) AS PROVIDER_NPI
FROM X12_EDI_AI.SILVER.SILVER_X12_SEGMENTS
WHERE SEGMENT_ID = 'NM1' AND SPLIT_PART(SEGMENT_DATA, '*', 2) IN ('85', '82', '41');

CREATE OR REPLACE DYNAMIC TABLE X12_EDI_AI.SILVER.SILVER_DIAGNOSES
    TARGET_LAG = '5 minutes'
    WAREHOUSE = APP_WH
AS
SELECT
    hi.MESSAGE_ID,
    icd.RAW_SEGMENT AS ICD10_CODE,
    'Principal' AS DIAGNOSIS_TYPE
FROM X12_EDI_AI.SILVER.SILVER_X12_SEGMENTS hi
JOIN X12_EDI_AI.SILVER.SILVER_X12_SEGMENTS icd
    ON hi.MESSAGE_ID = icd.MESSAGE_ID
    AND icd.SEGMENT_POSITION = hi.SEGMENT_POSITION + 1
WHERE hi.SEGMENT_ID = 'HI';

CREATE OR REPLACE DYNAMIC TABLE X12_EDI_AI.SILVER.SILVER_SERVICE_LINES
    TARGET_LAG = '5 minutes'
    WAREHOUSE = APP_WH
AS
SELECT
    sv.MESSAGE_ID,
    sv.SEGMENT_POSITION,
    SPLIT_PART(sld.RAW_SEGMENT, '*', 1) AS PROCEDURE_CODE,
    TRY_TO_DECIMAL(SPLIT_PART(sld.RAW_SEGMENT, '*', 2), 12, 2) AS LINE_CHARGE_AMOUNT,
    SPLIT_PART(sld.RAW_SEGMENT, '*', 3) AS UNIT_TYPE,
    TRY_TO_NUMBER(SPLIT_PART(sld.RAW_SEGMENT, '*', 4)) AS UNIT_COUNT,
    sv.SOURCE_SYSTEM,
    sv.INGESTION_TIMESTAMP
FROM X12_EDI_AI.SILVER.SILVER_X12_SEGMENTS sv
JOIN X12_EDI_AI.SILVER.SILVER_X12_SEGMENTS sld
    ON sv.MESSAGE_ID = sld.MESSAGE_ID
    AND sld.SEGMENT_POSITION = sv.SEGMENT_POSITION + 1
WHERE sv.SEGMENT_ID = 'SV1';

------------------------------------------------------------------------
-- GOLD LAYER
------------------------------------------------------------------------

CREATE SCHEMA IF NOT EXISTS X12_EDI_AI.GOLD;

CREATE OR REPLACE DYNAMIC TABLE X12_EDI_AI.GOLD.GOLD_CLAIMS_COMPLETE
    TARGET_LAG = '10 minutes'
    WAREHOUSE = APP_WH
AS
SELECT
    c.MESSAGE_ID,
    c.CLAIM_ID,
    c.TOTAL_BILLED_AMOUNT,
    c.PLACE_OF_SERVICE_CODE,
    p.PATIENT_LAST_NAME,
    p.PATIENT_FIRST_NAME,
    p.MEMBER_ID,
    p.DATE_OF_BIRTH,
    p.GENDER,
    bp.PROVIDER_NAME AS BILLING_PROVIDER_NAME,
    bp.PROVIDER_NPI AS BILLING_PROVIDER_NPI,
    rp.PROVIDER_NAME AS RENDERING_PROVIDER_NAME,
    rp.PROVIDER_NPI AS RENDERING_PROVIDER_NPI,
    d.ICD10_CODE AS PRIMARY_DIAGNOSIS_CODE,
    COUNT(DISTINCT sl.SEGMENT_POSITION) AS SERVICE_LINE_COUNT,
    c.SOURCE_SYSTEM,
    c.INGESTION_TIMESTAMP
FROM X12_EDI_AI.SILVER.SILVER_CLAIMS_HEADER c
LEFT JOIN X12_EDI_AI.SILVER.SILVER_PATIENTS p ON c.MESSAGE_ID = p.MESSAGE_ID
LEFT JOIN X12_EDI_AI.SILVER.SILVER_PROVIDERS bp ON c.MESSAGE_ID = bp.MESSAGE_ID AND bp.PROVIDER_ROLE = 'Billing'
LEFT JOIN X12_EDI_AI.SILVER.SILVER_PROVIDERS rp ON c.MESSAGE_ID = rp.MESSAGE_ID AND rp.PROVIDER_ROLE = 'Rendering'
LEFT JOIN X12_EDI_AI.SILVER.SILVER_DIAGNOSES d ON c.MESSAGE_ID = d.MESSAGE_ID
LEFT JOIN X12_EDI_AI.SILVER.SILVER_SERVICE_LINES sl ON c.MESSAGE_ID = sl.MESSAGE_ID
GROUP BY
    c.MESSAGE_ID, c.CLAIM_ID, c.TOTAL_BILLED_AMOUNT, c.PLACE_OF_SERVICE_CODE,
    p.PATIENT_LAST_NAME, p.PATIENT_FIRST_NAME, p.MEMBER_ID, p.DATE_OF_BIRTH, p.GENDER,
    bp.PROVIDER_NAME, bp.PROVIDER_NPI,
    rp.PROVIDER_NAME, rp.PROVIDER_NPI,
    d.ICD10_CODE, c.SOURCE_SYSTEM, c.INGESTION_TIMESTAMP;

CREATE OR REPLACE DYNAMIC TABLE X12_EDI_AI.GOLD.GOLD_CLAIMS_AI_ENRICHED
    TARGET_LAG = '30 minutes'
    WAREHOUSE = APP_WH
AS
WITH enrichment AS (
    SELECT gc.*,
        TRY_PARSE_JSON(
            AI_COMPLETE('claude-sonnet-4-6',
                'You are a medical coding expert. Given this ICD-10 code, return a JSON object with keys: "description" (human-readable diagnosis name), "category" (broad category like Respiratory, Cardiovascular, Musculoskeletal, Endocrine, Gastrointestinal, Infectious, Neoplasm, Injury, Mental Health, Other), "chronic" (true/false). Return ONLY valid JSON, no explanation. ICD-10 code: ' || COALESCE(gc.PRIMARY_DIAGNOSIS_CODE, 'Z00.00')
            )
        ) AS AI_ENRICHMENT
    FROM X12_EDI_AI.GOLD.GOLD_CLAIMS_COMPLETE gc
)
SELECT
    MESSAGE_ID,
    CLAIM_ID,
    TOTAL_BILLED_AMOUNT,
    PLACE_OF_SERVICE_CODE,
    PATIENT_LAST_NAME,
    PATIENT_FIRST_NAME,
    MEMBER_ID,
    DATE_OF_BIRTH,
    GENDER,
    BILLING_PROVIDER_NAME,
    BILLING_PROVIDER_NPI,
    RENDERING_PROVIDER_NAME,
    RENDERING_PROVIDER_NPI,
    PRIMARY_DIAGNOSIS_CODE,
    AI_ENRICHMENT:description::VARCHAR AS DIAGNOSIS_DESCRIPTION,
    AI_ENRICHMENT:category::VARCHAR AS DIAGNOSIS_CATEGORY,
    AI_ENRICHMENT:chronic::BOOLEAN AS IS_CHRONIC_CONDITION,
    SERVICE_LINE_COUNT,
    SOURCE_SYSTEM,
    INGESTION_TIMESTAMP
FROM enrichment;

------------------------------------------------------------------------
-- SAMPLE ANALYTICS QUERY
------------------------------------------------------------------------

SELECT
    DIAGNOSIS_CATEGORY,
    COUNT(*) AS CLAIM_COUNT,
    ROUND(AVG(TOTAL_BILLED_AMOUNT), 2) AS AVG_BILLED,
    ROUND(SUM(TOTAL_BILLED_AMOUNT), 2) AS TOTAL_BILLED,
    SUM(CASE WHEN IS_CHRONIC_CONDITION THEN 1 ELSE 0 END) AS CHRONIC_COUNT
FROM X12_EDI_AI.GOLD.GOLD_CLAIMS_AI_ENRICHED
WHERE DIAGNOSIS_DESCRIPTION IS NOT NULL
GROUP BY DIAGNOSIS_CATEGORY
ORDER BY CLAIM_COUNT DESC;
